# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += gui core widgets
TEMPLATE = app
TARGET = MD5Dialog
DESTDIR = ../x64/Debug
CONFIG += debug c++14
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./moc
OBJECTS_DIR += debug
UI_DIR += ./ui_files
RCC_DIR += ./rcc
CODECFORSRC = UTF_8
include(MD5Dialog.pri)
